version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - '3030:3030'
    volumes:
      - .:/app
